In [1]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2
print(result)

[5 7 9]


In [2]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
result = np.dot(matrix1, matrix2) # Матричное умножение
print(result)

[[19 22]
 [43 50]]


In [3]:
data = np.array([1, 2, 3, 4, 5])
mean = np.mean(data) # Среднее значение
std_dev = np.std(data) 
print(std_dev)

1.4142135623730951


In [4]:
v_vert_np = np.array([[1], [2]])
print(v_vert_np)

[[1]
 [2]]


In [5]:
m = np.matrix('1 2 3 4; 5 6 7 8; 9 1 5 7')
print(m)

[[1 2 3 4]
 [5 6 7 8]
 [9 1 5 7]]


In [6]:
arr = np.array([1, 2, 3, 4])
result = arr * 2
print(result)

[2 4 6 8]


In [7]:
A = np.matrix('1 -3; 2 5')
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 0.45454545  0.27272727]
 [-0.18181818  0.09090909]]


In [8]:
A = np.matrix('1. -3.; 2. 5.')
A_inv = np.linalg.inv(A)
A_inv_inv = np.linalg.inv(A_inv)
print(A)

[[ 1. -3.]
 [ 2.  5.]]


In [9]:
m = np.matrix('1 2 3 4; 5 6 7 8; 9 1 5 7')
print(m[1, :])

[[5 6 7 8]]


In [10]:
m = np.matrix('1 2 3 4; 5 6 7 8; 9 1 5 7')
print(m[0:2, 1:3])

[[2 3]
 [6 7]]


In [11]:
m = np.matrix('1 2 3 4; 5 6 7 8; 9 1 5 7')
print(type(m))

<class 'numpy.matrix'>


In [12]:
m = np.matrix('1 2 3 4; 5 6 7 8; 9 1 5 7')
print(m.max())

9


In [13]:
m = np.matrix('1 2 3 4; 5 6 7 8; 9 1 5 7')
print(m.max(axis=0))

[[9 6 7 8]]


In [14]:
nums = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(nums[nums < 5])

[1 2 3 4]


In [15]:
mas = np.arange(10)
print(mas)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
print(np.zeros((3, 4)))
print(np.eye(3))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(np.where(a % 2 == 0, a * 10, a / 10))

[ 0.   0.1 20.   0.3 40.   0.5 60.   0.7 80.   0.9]


In [18]:
x = np.linspace(0, 1, 5)
y = np.linspace(0, 2, 5)
xg, yg = np.meshgrid(x, y)
print(xg, '\n')
print(yg)

[[0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]] 

[[0.  0.  0.  0.  0. ]
 [0.5 0.5 0.5 0.5 0.5]
 [1.  1.  1.  1.  1. ]
 [1.5 1.5 1.5 1.5 1.5]
 [2.  2.  2.  2.  2. ]]


In [19]:
print(np.random.permutation(7))

[4 1 0 6 3 5 2]


In [20]:
arr_mix = np.random.permutation(arr)
index_mix = np.random.permutation(len(arr_mix))
print(index_mix)

[1 0 3 2]


In [21]:
v_hor_zeros_v2 = np.zeros((1, 5))
print(v_hor_zeros_v2 )
v_hor_one_v1 = np.ones((5,))
print(v_hor_one_v1)

[[0. 0. 0. 0. 0.]]
[1. 1. 1. 1. 1.]


In [22]:
v_vert_ones = np.ones((5, 1))
print(v_vert_ones)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [23]:
m_sqr = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
m_sqr_arr = np.array(m_sqr)
print(m_sqr_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
m_diag = [[1, 0, 0], [0, 5, 0], [0, 0, 9]]
m_diag_np = np.matrix(m_diag)
print(m_diag_np)

[[1 0 0]
 [0 5 0]
 [0 0 9]]


In [25]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
L = (A.dot(B)).T
R = (B.T).dot(A.T)
print(L)
print(R)

[[19 43]
 [22 50]]
[[19 43]
 [22 50]]


In [26]:
A = np.matrix('1 2; 3 4')
A_det = np.linalg.det(A)
A_T_det = np.linalg.det(A.T)
print(f"{A_det:.9f}")
print(f"{A_T_det:.9f}")

-2.000000000
-2.000000000


In [27]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
C = np.matrix('2 4; 7 8')
L = A.dot(B.dot(C))
R = (A.dot(B)).dot(C)
print(L)
print(R)

[[192 252]
 [436 572]]
[[192 252]
 [436 572]]


In [28]:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
det_A = round(np.linalg.det(A), 3)
det_A_t = round(np.linalg.det(A.T), 3)
print(det_A)
print(det_A_t)

-14.0
-14.0


In [29]:
A = np.matrix('-4 -1 2; -4 -1 2; 8 3 1')
B = np.matrix('-4 -1 2; 8 3 2; 8 3 1')
C = A.copy()
C[1, :] += B[1, :]
print(C)
print(B)

[[-4 -1  2]
 [ 4  2  4]
 [ 8  3  1]]
[[-4 -1  2]
 [ 8  3  2]
 [ 8  3  1]]


In [32]:
A = np.matrix('1 -3; 2 5')
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 0.45454545  0.27272727]
 [-0.18181818  0.09090909]]


In [31]:
m_eye = np.eye(4)
rank = np.linalg.matrix_rank(m_eye)
print(rank)

4
