## Задание 1

Создайте массив NumPy размером 3×3, содержащий числа от 1 до 9. Умножьте все элементы массива на 2, а затем замените все элементы больше 10 на 0. Выведите итоговый массив

In [1]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a = a*2
a[a>10]=0

print("Матрица с заменеными элементами ",'\n',  a)

Матрица с заменеными элементами  
 [[ 2  4  6]
 [ 8 10  0]
 [ 0  0  0]]


## Задание 2

Создайте массив NumPy из 20 случайных целых чисел от 1 до 100. Найдите и выведите все элементы, которые делятся на 5 без остатка. Затем замените их на -1 и выведите обновленный массив

In [3]:
a = np.random.randint(1, 100, 20)
print(a, '\n')

print("Элеметы делящиеся нацело на пять", a[a%5==0], '\n')

a[a%5==0]=-1

print("Массив с заменеными элементами", a)

[94 34 20 40 46 54 71 22 47 32 10 53  8 95 26 63 45  4 46 57] 

Элеметы делящиеся нацело на пять [20 40 10 95 45] 

Массив с заменеными элементами [94 34 -1 -1 46 54 71 22 47 32 -1 53  8 -1 26 63 -1  4 46 57]


## Задание 3

Создайте два массива NumPy размером 1×5, заполненные случайными числами от 0 до 50. Выведите все промежуточные и итоговые результаты.

In [4]:
a = np.random.randint(0, 50, size = (1, 5))
a1 = np.random.randint(0, 50, size = (1, 5))

result = np.vstack((a, a1))

b = result[0, :]
b1 = result[1, :]
print(a)
print(a1)
print()
print(result)
print()
print(b)
print(b1)

[[40 40 12 49 39]]
[[ 6 18 28 22 47]]

[[40 40 12 49 39]
 [ 6 18 28 22 47]]

[40 40 12 49 39]
[ 6 18 28 22 47]


## Задание 4

Создайте массив из 50 чисел, равномерно распределенных от -10 до 10. Вычислите сумму всех элементов, сумму положительных элементов и сумму отрицательных элементов. Выведите результаты

In [5]:
mas = np.random.uniform(-10, 10, 50)
print(mas, '\n')

summ=sum(mas)
sum_poz = sum(mas[mas>0])
sum_neg = sum(mas[mas<0]) 

print('Сумма = ', summ)
print('Сумма положительных = ', sum_poz)
print('Сумма отрицательных = ', sum_neg)

[ 2.29571102 -0.81210102 -0.42407866 -2.7155144   7.78303828  8.53979838
  9.38366683 -9.50694291 -0.01000901 -6.1592218  -9.65080495 -7.63011895
  1.34523391 -3.49778835  2.99694183  6.95866242 -9.60607233 -3.06220601
 -8.0810375  -7.15999822  9.04077963 -2.75859113 -4.26907829 -8.1857228
  4.35084963  9.08797259  5.14833299  0.3601734  -0.02290114 -4.02409132
  6.81357048 -9.56667674  3.44175237  7.15175532 -9.76533789 -1.73618589
  3.04204558 -6.37448979  1.83413357 -7.87801377  3.03238886  5.78518253
 -9.50532106 -1.20225521 -6.20207766  0.35942232 -5.09280209 -4.31350816
  5.49707544 -0.60715742] 

Сумма =  -45.57161708653687
Сумма положительных =  104.24848737283854
Сумма отрицательных =  -149.82010445937541


## Задание 5

Создайте: Единичную матрицу размером 4×4. Диагональную матрицу размером 4×4 с диагональными элементами [5, 10, 15, 20] (не использовать циклы). Найдите сумму всех элементов каждой из этих матриц и сравните результаты.

In [6]:
a = np.eye(4)
m = [5, 10, 15, 20]
m_diag = np.diag(m)
a1 = np.array(m_diag)

sum_el_a = np.sum(a)
sum_el_a1 = np.sum(a1)

print('Суммма  элементов матрицы a = ',sum_el_a) 
print('Суммма элементов мтарицы а1 = ', sum_el_a1)

Суммма  элементов матрицы a =  4.0
Суммма элементов мтарицы а1 =  50


## Задание 6

Создайте две квадратные матрицы NumPy размером 3×3, заполненные случайными целыми числами от 1 до 20. Вычислите и выведите: Их сумму Их разность Их поэлементное произведение

In [7]:
a = np.random.randint(1, 20, size=(3, 3))  
a1 = np.random.randint(1, 20, size=(3, 3))  

print('Сумма матриц',"\n",  a + a1, "\n")  
print('Разность матриц ', "\n", a - a1, "\n")  
print('Поэлементое произведение',"\n",  a * a1, "\n")

Сумма матриц 
 [[20 34 16]
 [19 25 35]
 [17  2 19]] 

Разность матриц  
 [[ 0  0 -4]
 [-9 -9 -3]
 [ 5  0 -7]] 

Поэлементое произведение 
 [[100 289  60]
 [ 70 136 304]
 [ 66   1  78]] 



## Задание 7

Создайте две матрицы NumPy: Первую размером 2×3, заполненную случайными числами от 1 до 10. Вторую размером 3×2, заполненную случайными числами от 1 до 10. Выполните матричное умножение (используя оператор @ или функцию np.dot) и выведите результат.

In [8]:
matrix1 = np.random.randint(1, 10, size = (2, 3))
matrix2 = np.random.randint(1, 10, size = (3, 2))

print(matrix1,'\n')
print(matrix2, '\n')
print(np.dot(matrix1, matrix2))

[[8 8 2]
 [4 9 3]] 

[[1 5]
 [8 3]
 [4 4]] 

[[80 72]
 [88 59]]


## Задание 8

Создайте случайную квадратную матрицу 3×3. Найдите и выведите: Определитель этой матрицы (используйте np.linalg.det). Обратную матрицу (используйте np.linalg.inv). Если матрица вырождена (определитель равен 0), выведите сообщение, что матрица вырождена.

In [10]:
matrix = np.random.randint(1, 20, size=(3, 3))
det = np.linalg.det(matrix)

if det == 0:
    print("матрица вырождена")

inv = np.linalg.inv(matrix)
print('Определитель = ', det)
print('Oбратная матица ','\n', inv)

Определитель =  9.999999999999993
Oбратная матица  
 [[  5.    1.5  -8. ]
 [ 10.8   3.5 -17.6]
 [ -8.   -2.5  13. ]]


## Задание 9

Создайте матрицу NumPy размером 4×4, содержащую случайные целые числа от 1 до 50. Выведите: Исходную матрицу Транспонированную матрицу След матрицы (сумму элементов на главной диагонали) Используйте np.trace для нахождения следа.

In [11]:
matrix = np.random.randint(1, 50, size = (4,4))
trace = np.trace(matrix)

print(matrix, '\n')
print('Транспонированная матрица', '\n', np.transpose(matrix), '\n')
print('След = ', trace)

[[17  9 48  7]
 [40 42 45 18]
 [26 15 31 10]
 [24 37 45 33]] 

Транспонированная матрица 
 [[17 40 26 24]
 [ 9 42 15 37]
 [48 45 31 45]
 [ 7 18 10 33]] 

След =  123


## Задание 10

Решите систему линейных уравнений вида:

$$
\begin{cases} 
2x + 3y - z = 5, \\ 
4x - y + 2z = 6, \\ 
-3x + 5y + 4z = -2. 
\end{cases}
$$

Используйте матричное представление Ax = B , где A – матрица коэффициентов, x – вектор неизвестных, B – вектор правой части. Решите систему с помощью np.linalg.solve и выведите результат

In [12]:
A = np.array([[2, 3, -1], [4, -1, 2], [-3, 5, 4]])
B = [5, 6, -2]

solution = np.linalg.solve(A, B)

print(solution)

[1.63963964 0.57657658 0.00900901]


## Решите индивидуальное задание согласно вашему варианту (16).

**Производственный процесс.** Три машины изготавливают детали. Первая
производит 5 деталей в минуту, вторая — 8, третья — 12. Завод должен
произвести 1000 деталей за минимальное время. Сколько времени должна
работать каждая машина, если первая должна проработать в два раза дольше,
чем вторая?
Мы получем уравнение по времени такого вида:
$$
\begin{cases} 
5t_1+8t_2+12t_3=1000, \\ 
t_1-2t_2=0, \\ 
t_1-t_3=0. 
\end{cases}
$$

In [13]:
import numpy as np

coeff_matrix = np.array([
    [5, 8, 12],
    [1, -2, 0],
    [1, 0, -1]
])

right_parts = np.array([1000, 0, 0])

def solve_cramer(A, B):
    main_det = np.linalg.det(A)
    if main_det == 0:
        return None
    
    solutions = []
    for i in range(len(B)):
        temp_matrix = A.copy()
        temp_matrix[:, i] = B
        solutions.append(np.linalg.det(temp_matrix) / main_det)
    
    return np.array(solutions)

def solve_matrix_inverse(A, B):
    try:
        A_inverse = np.linalg.inv(A)
        return A_inverse.dot(B)
    except:
        return None

def solve_numpy(A, B):
    try:
        return np.linalg.solve(A, B)
    except:
        return None

solution_cramer = solve_cramer(coeff_matrix, right_parts)
solution_inverse = solve_matrix_inverse(coeff_matrix, right_parts)
solution_numpy = solve_numpy(coeff_matrix, right_parts)

print("Результаты решения системы:")
print(f"Метод Крамера: t1={solution_cramer[0]:.1f}, t2={solution_cramer[1]:.1f}, t3={solution_cramer[2]:.1f}")
print(f"Матричный метод: t1={solution_inverse[0]:.1f}, t2={solution_inverse[1]:.1f}, t3={solution_inverse[2]:.1f}")
print(f"np.linalg.solve: t1={solution_numpy[0]:.1f}, t2={solution_numpy[1]:.1f}, t3={solution_numpy[2]:.1f}")

if np.allclose(solution_cramer, solution_inverse) and np.allclose(solution_inverse, solution_numpy):
    print("\nВсе методы дали одинаковые результаты")
else:
    print("\nРезультаты методов различаются")

Результаты решения системы:
Метод Крамера: t1=47.6, t2=23.8, t3=47.6
Матричный метод: t1=47.6, t2=23.8, t3=47.6
np.linalg.solve: t1=47.6, t2=23.8, t3=47.6

Все методы дали одинаковые результаты
